[plugins]
spotless = { id = "com.diffplug.spotless", version = "8.0.0" }
spotbugs = { id = "com.github.spotbugs", version = "6.2.6" }
buildtimetracker = { id = "com.asarkar.gradle.build-time-tracker", version = "5.0.1" }

[versions]
spotbugs = "4.9.4"
guava = "33.4.8-jre"
log4j = "2.25.3"
commons-lang = "3.18.0"
jackson = "2.20.0"
# test libs
junit = "5.13.4"
truth = "1.4.4"
mockito = "5.19.0"
# langs
scala = "3.7.2"
kotlin = "2.3.0"

[libraries]
spotbugs-annotations = { module = "com.github.spotbugs:spotbugs-annotations", version.ref = "spotbugs" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
log4j-core = { module = "org.apache.logging.log4j:log4j-core", version.ref = "log4j" }
commons-lang = { module = "org.apache.commons:commons-lang3", version.ref = "commons-lang" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
jackson-datatype-jsr310 = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310", version.ref = "jackson" }
jackson-datatype-guava = { module = "com.fasterxml.jackson.datatype:jackson-datatype-guava", version.ref = "jackson" }
# test libs
junit = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
truth = { module = "com.google.truth:truth", version.ref = "truth" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
mockito-junit = { module = "org.mockito:mockito-junit-jupiter", version.ref = "mockito" }
guava-testlib = { module = "com.google.guava:guava-testlib", version.ref = "guava" }
# scala
scala-library = { module = "org.scala-lang:scala3-library_3", version.ref = "scala" }
scala-parallel-collections = { module = "org.scala-lang.modules:scala-parallel-collections_3", version = "1.2.0" }
# kotlin
kotlin-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version = "1.10.1" }
